sum
js-tasks-ru/vue-20220125_yellow-sparrow pull request #1
Opened 2022-01-28 12:41 UTC by yellowSparrow

sum solution

2022-01-28 12:41 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @ShGKme должен запустить тесты.

2022-01-28 13:22 UTC, ShGKme commented
В PR есть конфликт слияния, его нельзя принять.

Выполните команды:
```git
git pull upstream master
git push origin master
```

2022-01-31 21:53 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-01-31 21:53 UTC, ShGKme requested changes
Требуется решить все добавленные задачи, чтобы PR  был принят

2022-02-01 13:11 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-01 13:11 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-02-01 13:11 UTC, merged