task 4/1
js-tasks-ru/vue-20220125_yellow-sparrow pull request #4
Opened 2022-02-11 19:03 UTC by yellowSparrow

2022-02-11 19:03 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-12 17:12 UTC, ShGKme requested changes
Изображение выводится некорректно...

2022-02-12 17:12 UTC, ShGKme commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
> +  background-image: linear-gradient(0deg, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), var(--default-cover), v-bind(cover);
Сейчас у элемента есть сразу три фона. Всегда три. Во-первых, при отсутствии изображения в стилях выводится некорректный `url(undefined)`, во-вторых, получается двойная картинка, выглядит странно :) 

![image](https://user-images.githubusercontent.com/25978914/153720927-f4caa0e4-e5be-4095-b7fb-9fd7d2dc14b3.png)

2022-02-12 17:12 UTC, ShGKme commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
> +  background-image: linear-gradient(0deg, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), var(--default-cover), v-bind(cover);
Требуется либо выводить изображение по ссылке `url(image)`, либо при его отсутствии изображение по умолчанию через `var(--default-cover)`. Но не то и другое одновременно. Для этого требуется проверка в вычисляемом свойстве и возврат одно из двух значений.

2022-02-14 06:51 UTC, yellowSparrow commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
> +  background-image: linear-gradient(0deg, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), var(--default-cover), v-bind(cover);
Добрый день, да, я это понимаю и пробовала именно так, не получилось нормально экранировать, как я и говорила, много времени потратила на синтаксис и не получилось. Поэтому подсмотрела решение, запушила обновление.

2022-02-14 06:57 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-14 21:35 UTC, ShGKme commented
Закрываю, как PR без изменений

2022-02-14 21:35 UTC, closed without merging